package: odo
user: blaze

platform:
  - linux-64
  - linux-32
  - osx-64
  - win-32
  - win-64
engine:
  - python=2.7
  - python=3.3
  - python=3.4

before_script:
  - python -V

install:
  - conda config --add channels blaze
  - conda config --set always_yes true

script:
  - conda build conda.recipe

env:
  - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

iotimeout: 120

build_targets: conda

notifications:
  email:
    recipients: ['ksmith@continuum.io', 'lransom@continuum.io']
